#ifndef SOUND_CONFIGURATIONS_H
#define SOUND_CONFIGURATIONS_H

//MENU MUSIC
#define THE_INITIUM_CAVERNS_MUSIC 0
#define LONG_AWAITED_MUSIC 1 
#define THE_ABYSS_MUSIC 2

#endif //SOUND_CONFIGURATIONS_H