#ifndef SOUND_CONFIGURATIONS_H
#define SOUND_CONFIGURATIONS_H

//MENU MUSIC
#define THE_INITIUM_CAVERNS_MUSIC 0
#define LONG_AWAITED_MUSIC 1 
#define THE_ABYSS_MUSIC 2
#define LASER_SHOOT_0 3
#define LASER_SHOOT_1 4
#define LASER_SHOOT_2 5
#define LASER_SHOOT_3 6
#define EXPLOSION_0 7
#define EXPLOSION_1 8
#define EXPLOSION_2 9
#define EXPLOSION_3 10

#endif //SOUND_CONFIGURATIONS_H